name: build image and push to docker hub
on: 
  push:
    branches:
      - main

# permissions:
#   id-token: write


# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
jobs:
  deploy_source:
    name: build and push docker image
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Extract metadata ( tags, labels ) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: jeffbuenting/k8s_mqtt

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}

